name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Minikube requires using its own Docker daemon
          eval $(minikube -p minikube docker-env)
          # Build the image using the Minikube daemon
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ettenheim_emc_lab_application:latest .
          # Push the image to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ettenheim_emc_lab_application:latest

      - name: Remove previous deployment
        run: |
          # kubectl delete deployment celery-worker --ignore-not-found
          kubectl delete service emc-lab-application --ignore-not-found
          kubectl delete deployment emc-lab-application --ignore-not-found
          sleep 10

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ettenheim_emc_lab_k8s/vi_mysql-storage.yaml
          kubectl apply -f ettenheim_emc_lab_k8s/db_deployment.yaml
          sleep 10
          kubectl apply -f ettenheim_emc_lab_k8s/app-deployment.yaml
          # kubectl apply -f ettenheim_emc_lab_k8s/redis.yaml
          # kubectl apply -f ettenheim_emc_lab_k8s/celery_worker.yaml

      # - name: Start port forwarding
      #   run: |
      #     sleep 10
      #     kubectl port-forward --address 0.0.0.0 service/emc-lab-application 8000:5000





















